version: "3.3"

services:
  es1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
    environment:
      - "cluster.name=elk"
      - "bootstrap.memory_lock=false"
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
      - "network.host=10.156.0.5"
      - "discovery.zen.ping.unicast.hosts=10.156.0.5,10.156.0.3,10.156.0.4"
      - "LOGSPOUT=ignore"
    pid: "host"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - host-net
    expose:
      - 9200
      - 9300
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 512M
      placement:
        constraints:
          - 'node.hostname==swarm-worker-1'

  es2:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
    environment:
      - "cluster.name=elk"
      - "bootstrap.memory_lock=false"
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
      - "network.host=10.156.0.3"
      - "discovery.zen.ping.unicast.hosts=10.156.0.5,10.156.0.3,10.156.0.4"
      - "LOGSPOUT=ignore"
    pid: "host"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - host-net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 512M
      placement:
        constraints:
          - 'node.hostname==swarm-worker-2'

  es3:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
    environment:
      - "cluster.name=elk"
      - "bootstrap.memory_lock=false"
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
      - "network.host=10.156.0.4"
      - "discovery.zen.ping.unicast.hosts=10.156.0.5,10.156.0.3,10.156.0.4"
      - "LOGSPOUT=ignore"
    pid: "host"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - host-net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 512M
      placement:
        constraints:
          - 'node.hostname==swarm-worker-3'

  es-router:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
    environment:
      - "cluster.name=elk"
      - "node.master=false"
      - "node.data=false"
      - "node.ingest=false"
      - "bootstrap.memory_lock=false"
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - "network.host=10.156.0.2"
      - "discovery.zen.ping.unicast.hosts=10.156.0.5,10.156.0.3,10.156.0.4"
      - "LOGSPOUT=ignore"
    pid: "host"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - host-net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
      placement:
        constraints:
          - 'node.hostname==swarm-manager-1'

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.0.0
    environment:
      - "ELASTICSEARCH_URL=http://10.156.0.2:9200"
      - "LOGSPOUT=ignore"
    networks:
      - net
    ports:
      - 5601:5601
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M
      placement:
        constraints:
          - 'node.hostname==swarm-worker-3'

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.0.0
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      - "LOGSPOUT=ignore"
    networks:
      - host-net
    expose:
      - 5000
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  logspout:
    image: stefanprodan/swarm-logspout-logstash
    environment:
      - "ROUTE_URIS=logstash+tcp://localhost:50005"
      - "LOGSPOUT=ignore"
      - "HTTP_PORT=55444"
      - "DOCKER_LABELS=on"
      - "RETRY_STARTUP=on"
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - host-net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M

  curator:
    image: stefanprodan/es-curator-cron
    environment:
      - "PERIOD=daily"
      - "KEEP_DAYS=45"
      - "INDEX_PREFIX=logstash"
    command: "--host 10.156.0.5 --port 9200"
    networks:
      - net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M
      placement:
        constraints:
          - 'node.hostname==swarm-worker-3'

  exporter:
    image: braedon/prometheus-es-exporter:0.4.3
    configs:
      - source: exporter_config
        target: /usr/src/app/exporter.cfg
    command: "-e 10.156.0.5"
    networks:
      - net
    ports:
      - 9206:9206
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M
      placement:
        constraints:
          - 'node.hostname==swarm-manager-1'

networks:
  host-net:
    external:
      name: "host"
  net:
    driver: overlay
    attachable: true

configs:
  logstash_config:
    file: logstash.yml
  logstash_pipeline:
    file: logstash.pipeline
  exporter_config:
    file: exporter.cfg
